### ISSUE TITLE
IzPack compilation ERROR

### ISSUE THREAD

**Issue by samirdouichi** [esofthead/mycollab#6] opened 2015-06-19 02:01 UTC
Hi team,

I 'm trying to get work the mycollab_release_5.0.7 in my windows 7 32 bits with a sun oracle JDK 1.8 with IntelliJ IDEA 14.1,by kindly fulfiling the community developpement guide i 'm stuged on the complitation process ,this is my issue

[ERROR] Failed to execute goal org.codehaus.izpack:izpack-maven-plugin:1.0-alpha-5:izpack (default) on project mycollab-app-community: IzPack compilation ERROR: D:\project\mycollab\mycollab-Release_5.0.7\mycollab-app-community\target\staging\install.xml:62: D:\project\mycollab\mycollab-Release_5.0.7\mycollab-app-community\target\staging\logs -> [Help 1]

I wonder if am 'i messing somthing in my project configuration?

Thank you in advence,

Samir

**Comment by haiphucnguyen** [comment] 2015-06-19 03:34
The problem may be caused by windows can not create an empty folder (MacOS or Unix does not have such issue). Could you try to get the latest source and confirm whether the issue has gone? Thank you

Hai Nguyen

**Comment by haiphucnguyen** [comment] 2015-06-22 08:38
Has your issue gone? I close this issue and open a new thread at http://support.mycollab.com/topic/780181-izpack-compilation-error/ if you have extra issue. Thank you.

Hai

**Closed by haiphucnguyen** 2015-06-22 08:38 UTC
